// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJfycj9RdXta7mTkAFD5zb3clhVofe_pY',
    appId: '1:780010401401:web:f9060bbd0b5da95aff2ea8',
    messagingSenderId: '780010401401',
    projectId: 'reddit-clone-3e1be',
    authDomain: 'reddit-clone-3e1be.firebaseapp.com',
    storageBucket: 'reddit-clone-3e1be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FEKI-OO8kdfe2njeE1yfVOGN5BkRwp0',
    appId: '1:780010401401:android:3bbc794d65d8c8baff2ea8',
    messagingSenderId: '780010401401',
    projectId: 'reddit-clone-3e1be',
    storageBucket: 'reddit-clone-3e1be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7iAbSDN6eVXeRr0AxmZ6vmI5D5E4ig3Q',
    appId: '1:780010401401:ios:b499a8c9fd4dc3d9ff2ea8',
    messagingSenderId: '780010401401',
    projectId: 'reddit-clone-3e1be',
    storageBucket: 'reddit-clone-3e1be.appspot.com',
    iosClientId: '780010401401-2vl1asaorpm92dpdilr5rgu9927kl3im.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7iAbSDN6eVXeRr0AxmZ6vmI5D5E4ig3Q',
    appId: '1:780010401401:ios:4758ca9241a57732ff2ea8',
    messagingSenderId: '780010401401',
    projectId: 'reddit-clone-3e1be',
    storageBucket: 'reddit-clone-3e1be.appspot.com',
    iosClientId: '780010401401-80c6tg7837mjjmaujfvqiek9je66o1ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
